### PR TITLE
Fix IETF Review / IESG Approval range

### LINKED ISSUE #38: Roman's comments
[Roman's full ballot](https://mailarchive.ietf.org/arch/msg/rats/0S-j2Wi_AXoFN63qoayhIfiNLN4/)

Relevant excerpt:

> ** Section 6.7
>    Optional parameters:  "eat_profile" (EAT profile in string format.
>       OIDs MUST use the dotted-decimal notation.  The parameter value is
>       case-insensitive.)
> 
> -- Is using [RFC2119](https://datatracker.ietf.org/doc/rfc2119/) key words in an IANA template the right thing to do?  Perhaps add this keyword to Section 3 instead:
> 
> OLD
> The value of the eat_profile claim is either an OID or a URI
> 
> NEW 
> The value of the eat_profile claim MUST be either an OID or a URI.  If an OID is used, it MUST use the dotted-decimal notation).
> 
> -- Why is there guidance in the IANA template about the OID, but nothing saying it also needs to be a URI?  It might be clearer to provide guidance on the format of this parameter in only one place (Section 3).
> 
> ** Section 6.9
>    TBD1..6 are to be assigned from the space 256..999.
> 
> s/999/9999/ as that is the full range for IETF Review code points.  Or is the request really to get a <1000 code point?

### PR DESCRIPTION
**Pull request by thomas-fossati**
Partially fix #38

### CODE REVIEW

**Review by henkbirkholz — APPROVED** [review]
not sure where this is going, exactly. no harm

**Comment by thomas-fossati** [comment]
> not sure where this is going, exactly. no harm

Most puzzling comment :-)

**Comment by henkbirkholz** [comment]
sometimes prophecies are only to be deciphered by the worthy :hammer:

**Comment by thomas-fossati** [comment]
> sometimes prophecies are only to be deciphered by the worthy 🔨

brushing up on my haruspicy skills!

**Pull request merged**
